# Generated by Django 5.2 on 2025-05-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TweetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='massege',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
